/*
  DZ Auto Trade product list
  --------------------------
  Simple way to add a product:
  1. Copy one product object between the { } brackets.
  2. Paste it before the closing ]; at the bottom.
  3. Change the text values: name, category, description, price, sku, availability, delivery.

  Category values must be one of:
  - avto-deli
  - cistila
  - orodja

  Set featured: true to show the product on the homepage.
  Set cartEnabled: true only for products with a fixed price that can be added to the cart now.
*/

window.products = [
  {
    "name": "Set filtrov za redni servis",
    "category": "avto-deli",
    "categoryLabel": "Avto deli",
    "description": "Oljni, zračni in kabinski filter za osnovno vzdrževanje vozila.",
    "price": "od 24,90 €",
    "badge": "Vzdrževanje",
    "sku": "DZ-FIL-001",
    "availability": "Na zalogi",
    "delivery": "1–3 delovne dni",
    "featured": true,
    "searchTerms": "servis filter oljni zračni kabinski vzdrževanje",
    "image": "data:image/svg+xml,%3Csvg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 200 200\"%3E%3Crect x=\"45\" y=\"30\" width=\"110\" height=\"140\" rx=\"18\" fill=\"%23dbeafe\"/%3E%3Cpath d=\"M70 55h60M70 78h60M70 101h60M70 124h60M70 147h60\" stroke=\"%234f9cff\" stroke-width=\"10\" stroke-linecap=\"round\"/%3E%3C/svg%3E",
    "theme": "linear-gradient(135deg, #1d4ed8, #0f172a)"
  },
  {
    "name": "Zavorne ploščice",
    "category": "avto-deli",
    "categoryLabel": "Avto deli",
    "description": "Preverjene ploščice za varno, tiho in zanesljivo zaviranje.",
    "price": "od 29,90 €",
    "badge": "Varnost",
    "sku": "DZ-BRK-001",
    "availability": "Po naročilu",
    "delivery": "2–5 delovnih dni",
    "featured": true,
    "searchTerms": "zavore ploščice varnost zavorne",
    "image": "data:image/svg+xml,%3Csvg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 200 200\"%3E%3Ccircle cx=\"100\" cy=\"100\" r=\"58\" fill=\"%23cbd5e1\"/%3E%3Ccircle cx=\"100\" cy=\"100\" r=\"25\" fill=\"%23111827\"/%3E%3Cpath d=\"M42 75c18-45 79-51 112-16l-22 22c-18-17-49-14-61 11z\" fill=\"%23f97316\"/%3E%3C/svg%3E",
    "theme": "linear-gradient(135deg, #7c2d12, #111827)"
  },
  {
    "name": "Brisalci in žarnice",
    "category": "avto-deli",
    "categoryLabel": "Avto deli",
    "description": "Potrošni deli za boljšo vidljivost v vseh vremenskih razmerah.",
    "price": "od 6,90 €",
    "badge": "Vidljivost",
    "sku": "DZ-VIS-001",
    "availability": "Na zalogi",
    "delivery": "1–3 delovne dni",
    "featured": false,
    "searchTerms": "brisalci žarnice vidljivost luči dež",
    "image": "data:image/svg+xml,%3Csvg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 200 200\"%3E%3Cpath d=\"M48 132c42-58 78-58 104 0\" fill=\"none\" stroke=\"%23e0f2fe\" stroke-width=\"16\" stroke-linecap=\"round\"/%3E%3Cpath d=\"M55 138h90\" stroke=\"%234f9cff\" stroke-width=\"12\" stroke-linecap=\"round\"/%3E%3Ccircle cx=\"145\" cy=\"58\" r=\"22\" fill=\"%23fde68a\"/%3E%3C/svg%3E",
    "theme": "linear-gradient(135deg, #075985, #0f172a)"
  },
  {
    "name": "Aktivni avto šampon",
    "category": "cistila",
    "categoryLabel": "Čistila",
    "description": "Koncentrirano čistilo za varno ročno pranje karoserije.",
    "price": "od 8,90 €",
    "badge": "Zunanjost",
    "sku": "DZ-CAR-001",
    "availability": "Na zalogi",
    "delivery": "1–3 delovne dni",
    "featured": true,
    "searchTerms": "šampon pranje zunanjost čistilo karoserija",
    "image": "data:image/svg+xml,%3Csvg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 200 200\"%3E%3Crect x=\"68\" y=\"42\" width=\"64\" height=\"118\" rx=\"14\" fill=\"%23bbf7d0\"/%3E%3Crect x=\"78\" y=\"26\" width=\"44\" height=\"26\" rx=\"8\" fill=\"%2332d583\"/%3E%3Ccircle cx=\"92\" cy=\"95\" r=\"10\" fill=\"white\"/%3E%3Ccircle cx=\"116\" cy=\"115\" r=\"14\" fill=\"white\"/%3E%3C/svg%3E",
    "theme": "linear-gradient(135deg, #166534, #0f172a)"
  },
  {
    "name": "Čistilo za notranjost",
    "category": "cistila",
    "categoryLabel": "Čistila",
    "description": "Za armaturo, plastiko, tekstil in prijeten občutek v kabini.",
    "price": "od 7,90 €",
    "badge": "Notranjost",
    "sku": "DZ-INT-001",
    "availability": "Na zalogi",
    "delivery": "1–3 delovne dni",
    "featured": false,
    "searchTerms": "notranjost armatura plastika tekstil kabina",
    "image": "data:image/svg+xml,%3Csvg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 200 200\"%3E%3Cpath d=\"M48 126h104l-14-44H62z\" fill=\"%23dbeafe\"/%3E%3Cpath d=\"M58 126v24m84-24v24\" stroke=\"%234f9cff\" stroke-width=\"14\" stroke-linecap=\"round\"/%3E%3Ccircle cx=\"75\" cy=\"138\" r=\"12\" fill=\"%23111827\"/%3E%3Ccircle cx=\"125\" cy=\"138\" r=\"12\" fill=\"%23111827\"/%3E%3C/svg%3E",
    "theme": "linear-gradient(135deg, #0f766e, #0f172a)"
  },
  {
    "name": "Vosek in zaščitni premaz",
    "category": "cistila",
    "categoryLabel": "Čistila",
    "description": "Dodaten sijaj in zaščita laka pred umazanijo in vodo.",
    "price": "od 12,90 €",
    "badge": "Zaščita",
    "sku": "DZ-WAX-001",
    "availability": "Po naročilu",
    "delivery": "2–5 delovnih dni",
    "featured": false,
    "searchTerms": "vosek zaščitni premaz lak sijaj voda",
    "image": "data:image/svg+xml,%3Csvg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 200 200\"%3E%3Cpath d=\"M100 30l52 24v38c0 36-21 62-52 78-31-16-52-42-52-78V54z\" fill=\"%23bfdbfe\"/%3E%3Cpath d=\"M78 101l16 16 32-40\" fill=\"none\" stroke=\"%234f9cff\" stroke-width=\"12\" stroke-linecap=\"round\"/%3E%3C/svg%3E",
    "theme": "linear-gradient(135deg, #1e40af, #0f172a)"
  },
  {
    "name": "Komplet nasadnih ključev",
    "category": "orodja",
    "categoryLabel": "Orodja",
    "description": "Osnovni komplet za servis, montažo in domačo garažo.",
    "price": "od 39,90 €",
    "badge": "Ročno orodje",
    "sku": "DZ-TOL-001",
    "availability": "Na zalogi",
    "delivery": "1–3 delovne dni",
    "featured": false,
    "searchTerms": "nasadni ključi orodje komplet garaža",
    "image": "data:image/svg+xml,%3Csvg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 200 200\"%3E%3Crect x=\"38\" y=\"58\" width=\"124\" height=\"84\" rx=\"16\" fill=\"%23cbd5e1\"/%3E%3Cpath d=\"M62 84h76M62 108h76\" stroke=\"%23111827\" stroke-width=\"12\" stroke-linecap=\"round\"/%3E%3C/svg%3E",
    "theme": "linear-gradient(135deg, #374151, #0f172a)"
  },
  {
    "name": "OBD čitalnik napak",
    "category": "orodja",
    "categoryLabel": "Orodja",
    "description": "Hitra osnovna diagnostika opozorilnih lučk in napak motorja.",
    "price": "od 24,90 €",
    "badge": "Diagnostika",
    "sku": "DZ-OBD-001",
    "availability": "Na zalogi",
    "delivery": "1–3 delovne dni",
    "featured": true,
    "searchTerms": "obd diagnostika čitalnik napake motor",
    "image": "data:image/svg+xml,%3Csvg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 200 200\"%3E%3Crect x=\"50\" y=\"42\" width=\"100\" height=\"116\" rx=\"18\" fill=\"%23dbeafe\"/%3E%3Crect x=\"68\" y=\"64\" width=\"64\" height=\"34\" rx=\"8\" fill=\"%23111827\"/%3E%3Cpath d=\"M76 124h48\" stroke=\"%234f9cff\" stroke-width=\"12\" stroke-linecap=\"round\"/%3E%3C/svg%3E",
    "theme": "linear-gradient(135deg, #4338ca, #0f172a)"
  },
  {
    "name": "Dvigalka in stojala",
    "category": "orodja",
    "categoryLabel": "Orodja",
    "description": "Varnejše delo pri menjavi koles, pregledih in lažjih popravilih.",
    "price": "od 49,90 €",
    "badge": "Delavnica",
    "sku": "DZ-LFT-001",
    "availability": "Po naročilu",
    "delivery": "2–5 delovnih dni",
    "featured": false,
    "searchTerms": "dvigalka stojala delavnica kolesa varnost",
    "image": "data:image/svg+xml,%3Csvg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 200 200\"%3E%3Cpath d=\"M50 142h100L100 58z\" fill=\"%23fed7aa\"/%3E%3Cpath d=\"M74 142l26-44 26 44\" fill=\"none\" stroke=\"%23f97316\" stroke-width=\"12\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/%3E%3C/svg%3E",
    "theme": "linear-gradient(135deg, #9a3412, #0f172a)"
  },
  {
    "name": "CarPro Iron.X 500ml",
    "category": "cistila",
    "categoryLabel": "Čistila",
    "description": "Čistilo za zračno rjo in kovinske delce na laku ter platiščih.",
    "price": "13,69 €",
    "regularPrice": "",
    "supplierPrice": "11,98 €",
    "badge": "Dekontaminacija",
    "sku": "2026-01",
    "availability": "Na zalogi",
    "delivery": "1–3 delovne dni",
    "shippingNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "purchaseUrl": "https://www.operi-avto.si/cistila-za-zracno-rjo/940-iron-x-univerzalno-cistilno-sredstvo.html",
    "brand": "CarPro",
    "compatibility": "univerzalno za nego vozila",
    "orderNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "checkoutEnabled": true,
    "cartEnabled": true,
    "checkoutAmount": 1369,
    "featured": true,
    "searchTerms": "iron x ironx zračna rja kovinski delci platišča carpro",
    "image": "images/products/iron-x-univerzalno-cistilno-sredstvo.jpg",
    "imageAlt": "CarPro Iron.X 500ml",
    "theme": "linear-gradient(135deg, #991b1b, #0f172a)"
  },
  {
    "name": "CarPro TarX 500ml",
    "category": "cistila",
    "categoryLabel": "Čistila",
    "description": "Sredstvo za odstranjevanje katrana, smole in ostankov lepil z vozila.",
    "price": "17,95 €",
    "regularPrice": "",
    "supplierPrice": "14,36 €",
    "badge": "Katranska umazanija",
    "sku": "2026-02",
    "availability": "Na zalogi",
    "delivery": "1–3 delovne dni",
    "shippingNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "purchaseUrl": "https://www.operi-avto.si/odstranjevanje-smole-in-lepil/1125-carpro-tar-x-500ml.html",
    "brand": "CarPro",
    "compatibility": "univerzalno za nego vozila",
    "orderNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "checkoutEnabled": true,
    "cartEnabled": true,
    "checkoutAmount": 1795,
    "featured": true,
    "searchTerms": "tarx tar x katran smola lepilo carpro detailing",
    "image": "data:image/svg+xml,%3Csvg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 200 200\"%3E%3Crect x=\"64\" y=\"34\" width=\"72\" height=\"130\" rx=\"18\" fill=\"%23fed7aa\"/%3E%3Crect x=\"78\" y=\"20\" width=\"44\" height=\"28\" rx=\"8\" fill=\"%23f97316\"/%3E%3Cpath d=\"M84 112c12-28 24-44 24-44s18 28 18 48a21 21 0 0 1-42 0z\" fill=\"%237c2d12\"/%3E%3C/svg%3E",
    "imageAlt": "CarPro TarX 500ml",
    "theme": "linear-gradient(135deg, #9a3412, #111827)"
  },
  {
    "name": "ValetPRO Bilberry Wheel Cleaner 5L",
    "category": "cistila",
    "categoryLabel": "Čistila",
    "description": "Bilberry Wheel Cleaner je učinkovito alkalno čistilo za vse vrste platišč. Odlično odstranjuje vse vrste umazanij ter tudi lažje zapečen zavorni prah. Čistilo se lahko uporablja tudi za odstranjevanje starih voskov in premazov. Sredstvo je koncentrirano in ga je pred uporabo potrebno zredčiti z vodo.\n\nNavodila za uporabo:\nSredstvo pred uporabo zredčite z vodo v razmerju od 1:3 do 1:10, odvisno od umazanije. Platišče sperite z vodo in nanj napršite Bilberry. Pustite nekaj časa, da čistilo začne delovati ter nato površino sperite z vodo. Za bolj umazana platišča priporočamo uporabo krtače, gobe ali čopiča.\n\nVarnostni napotki:\nVsebuje: Natrijev hidroksid; alkohol etoksilirani. Nevarno: H314 Povzroča hude opekline kože in poškodbe oči. P102 Hraniti zunaj dosega otrok. P260 Ne vdihavati razpršila. P264 Po uporabi temeljito umiti roke. P280 Nositi zaščitne rokavice/zaščitno obleko/zaščito za oči/zaščito za obraz. P301+330+331 PRI ZAUŽITJU: izprati usta. NE izzvati bruhanja. P303+361+353: PRI STIKU S KOŽO (ali lasmi): takoj odstraniti/sleči vsa kontaminirana oblačila. Izprati kožo z vodo/prho. P304+340: PRI VDIHAVANJU: prenesti žrtev na svež zrak in jo pustiti počivati v položaju, ki olajša dihanje. P305+351+338 PRI STIKU Z OČMI: previdno izpirajte z vodo nekaj minut. Odstranite kontaktne leče, če jih imate in če to lahko storite brez težav. Nadaljujte z izpiranjem. P315 Takoj poiščite zdravniško pomoč/oskrbo. P405 Hraniti zaklenjeno. Sestavine po Uredbi o detergentih EC 648/2004 < 5%: anionske površinsko aktivne snovi, < 5% amfoterne površinsko aktivne snovi, 5% - <15% ne ionske površinsko aktivne snovi.",
    "price": "35,99 €",
    "regularPrice": "36,97 €",
    "supplierPrice": "29,58 €",
    "badge": "Platišča",
    "sku": "DZ-03",
    "availability": "Na zalogi",
    "delivery": "1–3 delovne dni",
    "shippingNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "brand": "ValetPRO",
    "compatibility": "univerzalno za nego vozila",
    "orderNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "checkoutEnabled": true,
    "cartEnabled": true,
    "checkoutAmount": 3599,
    "featured": true,
    "searchTerms": "bilberry wheel cleaner platišča valetpro koncentrat alkalno čistilo zavorni prah voski premazi",
    "image": "images/products/bilberry-wheel-cleaner-5l.avif",
    "imageAlt": "ValetPRO Bilberry Wheel Cleaner 5L",
    "theme": "linear-gradient(135deg, #1e3a8a, #0f172a)"
  },
  {
    "name": "Gyeon Q2M Iron Redefined 500ml",
    "category": "cistila",
    "categoryLabel": "Čistila",
    "description": "pH-nevtralno čistilo za odstranjevanje železnih delcev z laka in platišč.",
    "price": "13,99 €",
    "regularPrice": "14,97 €",
    "supplierPrice": "11,23 €",
    "badge": "Dekontaminacija",
    "sku": "2026-04",
    "availability": "Na zalogi",
    "delivery": "1–3 delovne dni",
    "shippingNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "purchaseUrl": "https://www.operi-avto.si/cistila-za-zracno-rjo/2116-gyeon-q2m-iron-redifined-500ml.html",
    "brand": "Gyeon",
    "compatibility": "univerzalno za nego vozila",
    "orderNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "checkoutEnabled": true,
    "cartEnabled": true,
    "checkoutAmount": 1399,
    "featured": false,
    "searchTerms": "gyeon q2m iron redefined zračna rja železni delci",
    "image": "data:image/svg+xml,%3Csvg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 200 200\"%3E%3Crect x=\"62\" y=\"34\" width=\"76\" height=\"130\" rx=\"18\" fill=\"%23fee2e2\"/%3E%3Crect x=\"78\" y=\"20\" width=\"44\" height=\"28\" rx=\"8\" fill=\"%23dc2626\"/%3E%3Cpath d=\"M74 106h52\" stroke=\"%23dc2626\" stroke-width=\"14\" stroke-linecap=\"round\"/%3E%3Ccircle cx=\"100\" cy=\"106\" r=\"24\" fill=\"%23fecaca\"/%3E%3C/svg%3E",
    "imageAlt": "Gyeon Q2M Iron Redefined 500ml",
    "theme": "linear-gradient(135deg, #b91c1c, #111827)"
  },
  {
    "name": "Wekem Profi razpršilec za topila",
    "category": "cistila",
    "categoryLabel": "Čistila",
    "description": "Wekem Profi razpršilec za topila je razpršilka namenjena za prave profesionalce. Izdelan je iz izredno odpornega materiala s tesnili, odpornimi na kisline in topila. Volumen razpršilke je 1000 ml. Izredno primeren za čistilo za zavore.",
    "price": "42,99 €",
    "badge": "Profi razpršilec",
    "sku": "DZ-CP07",
    "availability": "Na zalogi",
    "delivery": "1–3 delovne dni",
    "shippingNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "brand": "Wekem",
    "compatibility": "za topila, kisline in čistila za zavore",
    "orderNote": "Volumen 1000 ml; primerno za profesionalno uporabo.",
    "checkoutEnabled": true,
    "cartEnabled": true,
    "checkoutAmount": 4299,
    "featured": false,
    "searchTerms": "wekem profi razpršilec topila kisline čistilo za zavore 1000 ml profesionalno",
    "image": "images/products/wekem-profi-razprsilec-za-topila-.avif",
    "imageAlt": "Wekem Profi razpršilec za topila 1000 ml",
    "theme": "linear-gradient(135deg, #1d4ed8, #111827)"
  },
  {
    "name": "K2 Roton PRO",
    "category": "cistila",
    "categoryLabel": "Čistila",
    "description": "K2 Roton PRO je profesionalno detailing sredstvo za čiščenje platišč in odstranjevanje kovinskih delcev oziroma zračne rje iz lakiranih površin vozila. pH-nevtralna formula je varna za uporabo na vseh površinah, tudi na poliranih platiščih. Čistilo vsebuje indikator delovanja in se ob stiku s kovinskim delcem obarva rdeče. Deluje hitro in učinkovito, plastenka z merilno skalo omogoča nadzor nad vsebino, kakovostna pršilna glava pa omogoča dve vrsti curka in enakomeren nanos.\n\nNavodila za uporabo:\nSredstvo napršite na suho in ohlajeno površino. Pustite delovati 2–3 minute, da čistilo reagira s kovinskimi delci. V primeru kontaminacije se bo čistilo obarvalo rdeče. Za odstranjevanje trdovratnejših delcev si lahko pomagate z gobo ali krpo. Vozilo dobro sperite in operite s šamponom.\n\nVarnostni napotki:\nVsebuje alkohole C12-14, etoksilirane sulfate, natrijeve soli in natrijev merkaptoacetat. Nevarno: H315 Povzroča draženje kože. H318 Povzroča hude poškodbe oči. H317 Lahko povzroči alergijski odziv kože. P102 Hraniti zunaj dosega otrok. P280 Nositi zaščitne rokavice / zaščito za oči / zaščito za obraz. P264 Po uporabi temeljito umiti roke. P305 + P351 + P338 – PRI STIKU Z OČMI: previdno izpirajte z vodo nekaj minut. Odstranite kontaktne leče, če jih imate in če to lahko storite brez težav. Nadaljujte z izpiranjem. P302 + P352 PRI STIKU S KOŽO: umiti z veliko mila in vode. P501 Odstraniti vsebino/posodo v skladu z nacionalnimi predpisi. Sestavine po Uredbi o detergentih EC 648/2004 (>15%-<30%): neionske površinsko aktivne snovi; parfumi.",
    "price": "13,97 €",
    "badge": "Platišča",
    "sku": "DZ-CP016",
    "availability": "Na zalogi",
    "delivery": "1–3 delovne dni",
    "shippingNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "brand": "K2",
    "compatibility": "platišča in lakirane površine vozila",
    "orderNote": "pH-nevtralno čistilo z indikatorjem delovanja.",
    "checkoutEnabled": true,
    "cartEnabled": true,
    "checkoutAmount": 1397,
    "featured": false,
    "searchTerms": "k2 roton pro platišča zračna rja kovinski delci ph nevtralno detailing indikator rdeče",
    "image": "images/products/k2-roton-pro-1000ml.avif",
    "imageAlt": "K2 Roton PRO čistilo za platišča 1000 ml",
    "theme": "linear-gradient(135deg, #dc2626, #111827)"
  },
  {
    "name": "K2 Felix 750ml",
    "category": "cistila",
    "categoryLabel": "Čistila",
    "description": "Pripravljeno čistilo za platišča in trdovratno umazanijo pri zunanjem čiščenju.",
    "price": "4,59 €",
    "regularPrice": "4,97 €",
    "supplierPrice": "3,23 €",
    "badge": "Platišča",
    "sku": "2026-05",
    "availability": "Na zalogi",
    "delivery": "1–3 delovne dni",
    "shippingNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "purchaseUrl": "https://www.operi-avto.si/pripravljeno-za-uporabo/50-k2-felix-5906534000781.html",
    "brand": "K2",
    "compatibility": "univerzalno za nego vozila",
    "orderNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "checkoutEnabled": true,
    "cartEnabled": true,
    "checkoutAmount": 459,
    "featured": false,
    "searchTerms": "k2 felix platišča pripravljeno čistilo zunanjost",
    "image": "data:image/svg+xml,%3Csvg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 200 200\"%3E%3Cpath d=\"M62 48h76l-8 112H70z\" fill=\"%23bbf7d0\"/%3E%3Crect x=\"76\" y=\"30\" width=\"48\" height=\"26\" rx=\"8\" fill=\"%2316a34a\"/%3E%3Cpath d=\"M82 96h36M82 122h36\" stroke=\"white\" stroke-width=\"10\" stroke-linecap=\"round\"/%3E%3C/svg%3E",
    "imageAlt": "K2 Felix 750ml",
    "theme": "linear-gradient(135deg, #15803d, #0f172a)"
  }
];
