window.products = [
  {
    "name": "CarPro Iron.X 500ml",
    "category": "cistila",
    "categoryLabel": "Čistila",
    "description": "Čistilo za zračno rjo in kovinske delce na laku ter platiščih.",
    "price": "13,69 €",
    "regularPrice": "",
    "supplierPrice": "11,98 €",
    "badge": "Dekontaminacija",
    "sku": "2026-01",
    "availability": "Dobavljivo pri dobavitelju – potrdimo pred naročilom",
    "delivery": "Po potrditvi dobavitelja",
    "shippingNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "purchaseUrl": "https://www.operi-avto.si/cistila-za-zracno-rjo/940-iron-x-univerzalno-cistilno-sredstvo.html",
    "brand": "CarPro",
    "compatibility": "univerzalno za nego vozila",
    "orderNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "checkoutEnabled": true,
    "checkoutAmount": 1369,
    "featured": true,
    "searchTerms": "iron x ironx zračna rja kovinski delci platišča carpro",
    "image": "images/products/iron-x-univerzalno-cistilno-sredstvo.jpg",
    "imageAlt": "CarPro Iron.X 500ml",
    "theme": "linear-gradient(135deg, #991b1b, #0f172a)",
    "cartEnabled": true
  },
  {
    "name": "CarPro TarX 500ml",
    "category": "cistila",
    "categoryLabel": "Čistila",
    "description": "Sredstvo za odstranjevanje katrana, smole in ostankov lepil z vozila.",
    "price": "17,95 €",
    "regularPrice": "",
    "supplierPrice": "14,36 €",
    "badge": "Katranska umazanija",
    "sku": "2026-02",
    "availability": "Dobavljivo pri dobavitelju – potrdimo pred naročilom",
    "delivery": "Po potrditvi dobavitelja",
    "shippingNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "purchaseUrl": "https://www.operi-avto.si/odstranjevanje-smole-in-lepil/1125-carpro-tar-x-500ml.html",
    "brand": "CarPro",
    "compatibility": "univerzalno za nego vozila",
    "orderNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "checkoutEnabled": true,
    "checkoutAmount": 1795,
    "featured": true,
    "searchTerms": "tarx tar x katran smola lepilo carpro detailing",
    "image": "images/products/carpro-tar-x-500ml.avif",
    "imageAlt": "CarPro TarX 500ml",
    "theme": "linear-gradient(135deg, #9a3412, #111827)",
    "cartEnabled": true
  },
  {
    "name": "ValetPRO Bilberry Wheel Cleaner 5L",
    "category": "cistila",
    "categoryLabel": "Čistila",
    "description": "Bilberry Wheel Cleaner je učinkovito alkalno čistilo za vse vrste platišč. Odlično odstranjuje vse vrste umazanij ter tudi lažje zapečen zavorni prah. Čistilo se lahko uporablja tudi za odstranjevanje starih voskov in premazov. Sredstvo je koncentrirano in ga je pred uporabo potrebno zredčiti z vodo.\n\nNavodila za uporabo:\nSredstvo pred uporabo zredčite z vodo v razmerju od 1:3 do 1:10, odvisno od umazanije. Platišče sperite z vodo in nanj napršite Bilberry. Pustite nekaj časa, da čistilo začne delovati ter nato površino sperite z vodo. Za bolj umazana platišča priporočamo uporabo krtače, gobe ali čopiča.\n\nVarnostni napotki:\nVsebuje: Natrijev hidroksid; alkohol etoksilirani. Nevarno: H314 Povzroča hude opekline kože in poškodbe oči. P102 Hraniti zunaj dosega otrok. P260 Ne vdihavati razpršila. P264 Po uporabi temeljito umiti roke. P280 Nositi zaščitne rokavice/zaščitno obleko/zaščito za oči/zaščito za obraz. P301+330+331 PRI ZAUŽITJU: izprati usta. NE izzvati bruhanja. P303+361+353: PRI STIKU S KOŽO (ali lasmi): takoj odstraniti/sleči vsa kontaminirana oblačila. Izprati kožo z vodo/prho. P304+340: PRI VDIHAVANJU: prenesti žrtev na svež zrak in jo pustiti počivati v položaju, ki olajša dihanje. P305+351+338 PRI STIKU Z OČMI: previdno izpirajte z vodo nekaj minut. Odstranite kontaktne leče, če jih imate in če to lahko storite brez težav. Nadaljujte z izpiranjem. P315 Takoj poiščite zdravniško pomoč/oskrbo. P405 Hraniti zaklenjeno. Sestavine po Uredbi o detergentih EC 648/2004 < 5%: anionske površinsko aktivne snovi, < 5% amfoterne površinsko aktivne snovi, 5% - <15% ne ionske površinsko aktivne snovi.",
    "price": "35,99 €",
    "regularPrice": "36,97 €",
    "supplierPrice": "29,58 €",
    "badge": "Platišča",
    "sku": "DZ-03",
    "availability": "Dobavljivo pri dobavitelju – potrdimo pred naročilom",
    "delivery": "Po potrditvi dobavitelja",
    "shippingNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "brand": "ValetPRO",
    "compatibility": "univerzalno za nego vozila",
    "orderNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "checkoutEnabled": true,
    "checkoutAmount": 3599,
    "featured": true,
    "searchTerms": "bilberry wheel cleaner platišča valetpro koncentrat alkalno čistilo zavorni prah voski premazi",
    "image": "images/products/bilberry-wheel-cleaner-5l.avif",
    "imageAlt": "ValetPRO Bilberry Wheel Cleaner 5L",
    "theme": "linear-gradient(135deg, #1e3a8a, #0f172a)",
    "cartEnabled": true
  },
  {
    "name": "Gyeon Q2M Iron Redifined 500ml",
    "category": "cistila",
    "categoryLabel": "Čistila",
    "description": "Gyeon Q2M Iron je eden izmed najučinkovitejših in najhitrejše delujočih odstranjevalcev kovinskih delcev na trgu. Izdelek je bil razvit posebej za odstranjevanje kontaminacije iz vozil kot je zavorni prah in ostali kovinski delci. Zaradi enostavne uporabe je izjemno priljubljen pri profesionalnih uporabnikih in entuziastih. Q2M Iron reagira izjemno hitro, kovinski delec spremeni v vodno topljiv kompleks, katerega enostavno sperete. Čistilo vsebuje indikator delovanja, ob stiku s kovinskim delcem se obarva rdeče. Sredstvo je pH nevtralno zato je popolnoma varno za uporabo na vseh površinah, tudi najobčutljivejših in poliranih platiščih. Q2M Iron lahko uporabljate na barvanih površinah, platiščih, steklih, in ostalih materialih. Ne povzroča poškodb na tesnilih ali kabrio strehah.\n\nPrednosti:\n- Enostaven in varen odstranjevalec kovinskih delcev\n- Gelasta formula omogoča boljši oprijem in daljši čas delovanja\n- Indikator delovanja, ob stiku z kovinskim delcem se obarva rdeče\n- Raztaplja kovinske delce, katere enostavno sperete z vozila\n- pH nevtralna formula je popolnoma varna za uporabo na barvi, kovinah, steklu ali plastikah\n- Vsebuje čistila, ki pospešijo čistilni proces\n- Prijetnejši vonj, kot konkurenčni izdelki\n\nNavodila za uporabo:\nPred uporabo se prepričajte, da je površina popolnoma ohlajena. Nanesite sredstvo na površino in pustite delovati 2-4 minute. Sredstvo se ob stiku z kontaminacijo obarva rdeče. Za odstranjevanje težje umazanije si lahko pomagate tudi z gobo ali krtačo. Površino nato dobro sperite z vodo.\n\nVarnostni napotki:\nVsebuje: Amonijev merkaptoacetat; metanol\nPozor: H302 Zdravju škodljivo pri zaužitju. H315 Povzroča draženje kože. H317 Lahko povzroči alergijski odziv kože. H319 Povzroča hudo draženje oči. H371 Lahko škoduje organom. P101 Če je potreben zdravniški nasvet, mora biti na voljo posoda ali etiketa proizvoda. P102 Hraniti zunaj dosega otrok. P260 Ne vdihavati prahu/dima/plina/meglice/hlapov/razpršila. P280 Nositi zaščitne rokavice/zaščitno obleko/zaščito za oči/zaščito za obraz. P405 Hraniti zaklenjeno. P501 Odstranjevanje odpadnih snovi v skladu uradnimi predpisi.",
    "price": "13,99 €",
    "regularPrice": "14,97 €",
    "supplierPrice": "11,23 €",
    "badge": "Dekontaminacija",
    "sku": "DZ-CP04",
    "availability": "Dobavljivo pri dobavitelju – potrdimo pred naročilom",
    "delivery": "Po potrditvi dobavitelja",
    "shippingNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "purchaseUrl": "https://www.operi-avto.si/cistila-za-zracno-rjo/2116-gyeon-q2m-iron-redifined-500ml.html",
    "brand": "Gyeon",
    "compatibility": "barvane površine, platišča, stekla, kovine in plastike",
    "orderNote": "pH-nevtralno čistilo za odstranjevanje kovinskih delcev z indikatorjem delovanja.",
    "checkoutEnabled": true,
    "checkoutAmount": 1399,
    "featured": false,
    "searchTerms": "gyeon q2m iron redifined redefined 500ml zračna rja kovinski delci zavorni prah platišča ph nevtralno dekontaminacija indikator rdeče",
    "image": "images/products/gyeon-q2m-iron-redifined-500ml.avif",
    "imageAlt": "Gyeon Q2M Iron Redifined 500ml",
    "theme": "linear-gradient(135deg, #b91c1c, #111827)",
    "cartEnabled": true
  },
  {
    "name": "KochChemie The Finisher Magic Shampoo 500ml",
    "category": "cistila",
    "categoryLabel": "Čistila",
    "description": "The Finisher Magic Shampoo je visoko napreden šampon za ročno pranje vozil, kateri združuje odlično čistilno moč ter dolgoročno zaščito v le enem koraku. Ne odstranjuje predhodno nanešenih voskov ali sealantov. Unikatna kombinacija sestavin za seboj pušča dolgotrajen zaščitni sloj in hidrofobno površino.\n\nPrednosti:\n- visok sijaj vozila po pranju\n- dolgotrajna zaščita laka le s pranjem\n- nano zaščitni delci\n\nNavodila za uporabo:\nZmešajte cca. 50ml šampona (5 zamaškov) z 10L tople vode. Vozilo operite od strehe navzdol ter sperite z cevjo ali visokozlačnim čistilcem. Vozilo do suhega obrišite z namensko krpo. Za lažje sušenje priporočamo uporabo sredstva KochChemie Allround Quick Shine, kateri zagotavlja dodaten sijaj in gladkost laka ter preprečuje nastanek prask med brisanjem.\n\nVarnostni napotki:\nPozor: H319 Povzroča hudo draženje oči. P101 Če je potreben zdravniški nasvet, mora biti na voljo posoda ali etiketa proizvoda. P102 Hraniti zunaj dosega otrok. P280 Nositi zaščitne rokavice/zaščitno obleko/zaščito za oči/zaščito za obraz. P305 + P351 + P338 – PRI STIKU Z OČMI: previdno izpirajte z vodo nekaj minut. Odstranite kontaktne leče, če jih imate in če to lahko storite brez težav. Nadaljujte z izpiranjem. P337 + P313 – Če draženje oči ne preneha: poiščite zdravniško pomoč/oskrbo. Sestavine po Uredbi o detergentih EC 648/2004 < 5%: kationsko površinsko aktivne snovi, 5-15% amfoterne površinsko aktivne snovi, ne ionske površinsko aktivne snovi, parfumi, linalol, benzisotiazolinon",
    "price": "13,97 €",
    "badge": "Šampon",
    "sku": "DZ-CP06",
    "availability": "Dobavljivo pri dobavitelju – potrdimo pred naročilom",
    "delivery": "Po potrditvi dobavitelja",
    "shippingNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "brand": "KochChemie",
    "compatibility": "ročno pranje vozil, lakirane površine in predhodno zaščitena vozila",
    "orderNote": "500 ml; šampon za ročno pranje z dolgotrajnim zaščitnim in hidrofobnim učinkom.",
    "checkoutEnabled": true,
    "cartEnabled": true,
    "checkoutAmount": 1397,
    "featured": false,
    "searchTerms": "kochchemie koch chemie the finisher magic shampoo 500ml nano magic šampon ročno pranje hidrofobna zaščita sijaj vosek sealant",
    "image": "images/products/kochchemie-nano-magic-shampoo-750ml.avif",
    "imageAlt": "KochChemie The Finisher Magic Shampoo 500ml",
    "theme": "linear-gradient(135deg, #0f766e, #111827)"
  },
  {
    "name": "Wekem Profi razpršilec za topila",
    "category": "cistila",
    "categoryLabel": "Čistila",
    "description": "Wekem Profi razpršilec za topila je razpršilka namenjena za prave profesionalce. Izdelan je iz izredno odpornega materiala s tesnili, odpornimi na kisline in topila. Volumen razpršilke je 1000 ml. Izredno primeren za čistilo za zavore.",
    "price": "42,99 €",
    "badge": "Profi razpršilec",
    "sku": "DZ-CP07",
    "availability": "Dobavljivo pri dobavitelju – potrdimo pred naročilom",
    "delivery": "Po potrditvi dobavitelja",
    "shippingNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "brand": "Wekem",
    "compatibility": "za topila, kisline in čistila za zavore",
    "orderNote": "Volumen 1000 ml; primerno za profesionalno uporabo.",
    "checkoutEnabled": true,
    "cartEnabled": true,
    "checkoutAmount": 4299,
    "featured": false,
    "searchTerms": "wekem profi razpršilec topila kisline čistilo za zavore 1000 ml profesionalno",
    "image": "images/products/wekem-profi-razprsilec-za-topila-.avif",
    "imageAlt": "Wekem Profi razpršilec za topila 1000 ml",
    "theme": "linear-gradient(135deg, #1d4ed8, #111827)"
  },
  {
    "name": "K2 Akra 750ml",
    "category": "cistila",
    "categoryLabel": "Čistila",
    "description": "Močno koncentrirano sredstvo za čiščenje zamaščenih površin okoli motorja. Aktivne sestavine omogočajo Hitro in učinkovito odstranjuje vse vrste olj, masti in druge nečistoče. Ne povzroča škode tesnilom in drugim elementom. Posebni dodatki varujejo pred korozijo površin. Kljub moči je izredno prijazen do okolja in uporabnika. Lahko ga uporabljamo tudi za čiščenje motornih koles, koles, žarov, strojnih delov,.....\n\nNavodila za uporabo: \nČistilo napršimo na umazano površino. Počakamo nekaj časa, da čistilo deluje in dobro speremo z vodo. Po potrebi zbrišemo še s krpo. Pri čiščenju motorjev vozila priporočamo, da po čiščenju motorni pokrov pustite še nekaj časa odprt, da se dobro posuši. Vodnega curka ne usmeriti direktno v elektronske komponente.\n\nVarnostni napotki:\nPred uporabo dobro preberite navodila in etiketo na plastenki. Vsebuje: D-Glukopiranoza, oligomeri, decil oktil glikozidi; Alkoholi, C12-15, etoksilirani, sulfati, natrijeve soli; Tetranatrijev etilendiaminotetraacetat. Nevarno: H315 Povzroča draženje kože. H318 Povzroča hude poškodbe oči. P102 Hraniti zunaj dosega otrok. P264 Po uporabi temeljito umiti roke. P280 Nositi zaščito za oči/obraz. P302 + P352 PRI STIKU S KOŽO: umiti z veliko vode. P305 + P351 + P338 PRI STIKU Z OČMI: previdno izpirajte z vodo nekaj minut. Odstranite kontaktne leče, če jih imate in če to lahko storite brez težav. Nadaljujte z izpiranjem. P501 Odstraniti vsebino/posodo v skladu z nacionalnimi predpisi.",
    "price": "4,97 €",
    "badge": "Motorni prostor",
    "sku": "DZ-CP08",
    "availability": "Dobavljivo pri dobavitelju – potrdimo pred naročilom",
    "delivery": "Po potrditvi dobavitelja",
    "shippingNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "brand": "K2",
    "compatibility": "motorni prostor, motorna kolesa, kolesa, žari in strojni deli",
    "orderNote": "750 ml; koncentrirano čistilo za zamaščene površine okoli motorja.",
    "checkoutEnabled": true,
    "cartEnabled": true,
    "checkoutAmount": 497,
    "featured": false,
    "searchTerms": "k2 akra 750ml motor motorni prostor maščoba olje nečistoče razmaščevalec tesnila korozija motorna kolesa kolesa žari strojni deli",
    "image": "images/products/k2-akra.avif",
    "imageAlt": "K2 Akra 750ml",
    "theme": "linear-gradient(135deg, #16a34a, #111827)"
  },
  {
    "name": "K2 Tar Remover 300ml",
    "category": "cistila",
    "categoryLabel": "Čistila",
    "description": "K2 Tar Remover je učinkovito in ekonomično sredstvo, ki z lahkoto odstranjuje katran in drevesno smolo iz vozil, pri tem pa ne poškoduje površin. Uporabljamo ga tam kjer ostala sredstva odpovedo. Odlikuje ga enostavna uporaba in izjemen čistilni učinek.\n\nNavodila za uporabo:\nSredstvo pred uporabo dobro pretresemo in napršimo neposredno na madež. Počakamo nekaj časa, da čistilo učinkuje in obrišemo z mehko in čisto krpo. Po čiščenju s K2 Tar Remover-jem priporočamo, da vozilo operete z nevtralnim šamponom za pranje vozil.\n\nVarnostni napotki:\nVsebuje: m-ksilen, p-ksilen, o-ksilen, etilbenzen Nevarno: H222 Zelo lahko vnetljiv aerosol. H315 Povzroča draženje kože. H312+H332 Zdravju škodljivo pri stiku s kožo ali pri vdihavanju. H229 Posoda je pod tlakom: lahko eksplodira pri segrevanju. P102 Hraniti zunaj dosega otrok. P210 Hraniti ločeno od vročine, vročih površin, isker, odprtega ognja in drugih virov vžiga. Kajenje prepovedano. P211 Ne pršiti proti odprtemu ognju ali drugemu viru vžiga. P251 Ne preluknjajte ali sežigajte je niti, ko je prazna. P260 Ne vdihavati meglice/hlapov/razpršila. P271 Uporabljati le zunaj ali v dobro prezračevanem prostoru. P410 + P412 Zaščititi pred sončno svetlobo. Ne izpostavljati temperaturam nad 50 °C/122 °F. P501 Odstraniti vsebino/posodo v skladu z nacionalnimi predpisi.",
    "price": "4,97 €",
    "badge": "Katran in smola",
    "sku": "DZ-CP09",
    "availability": "Dobavljivo pri dobavitelju – potrdimo pred naročilom",
    "delivery": "Po potrditvi dobavitelja",
    "shippingNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "brand": "K2",
    "compatibility": "katran in drevesna smola na zunanjih površinah vozila",
    "orderNote": "300 ml; odstranjevalec katrana in drevesne smole v aerosolu.",
    "checkoutEnabled": true,
    "cartEnabled": true,
    "checkoutAmount": 497,
    "featured": false,
    "searchTerms": "k2 tar remover 300ml katran drevesna smola odstranjevalec smole aerosol madeži čistilo zunanjost vozila",
    "image": "images/products/k2-tar-remover-300ml.avif",
    "imageAlt": "K2 Tar Remover 300ml",
    "theme": "linear-gradient(135deg, #334155, #111827)"
  },
  {
    "name": "Shiny Garage D-Tox 500ml",
    "category": "cistila",
    "categoryLabel": "Čistila",
    "description": "Shiny Garage D-Tox je močnejše čistilo, namenjeno odstranjevanju zapečenega zavornega prahu in zračne rje z lakiranih površin vozila. Izdelek vsebuje indikator delovanja, ob stiku z kovinskim delcem se obarva rdeče. Kljub njegovi moči je popolnoma varen za uporabo tudi na najobčutljivejših površinah.\n\nNavodila za uporabo:\nČiščenje platišč: Platišče najprej sperite z vodo. Nanesite na platišče ter pustite delovati nekaj trenutkov, dokler se čistilo ne obarva popolnoma rdeče. Pri čiščenju si lahko pomagate tudi s krtačko ali čopičem. Platišče nato še enkrat sperite z vodo, da odstranite vse ostanke čistila.\nČiščenje zračne rje: Vozilo dobro operite in popolnoma posušite. Nanesite čistilo na površino in počakajte, da se obarva rdeče. V primeru trdovratnejše rje priporočamo, da si pri čiščenju pomagate z gobo ali mokro mikro krpo. Vozilo nato še enkrat operite. Sredstvo se na površini ne sme zasušiti.\n\nVarnostni napotki:\nVsebuje: Natrijev merkaptoacetat. Pozor H317 Lahko povzroči alergijski odziv kože. P102 Hraniti zunaj dosega otrok. P280 Nositi zaščitne rokavice /zaščito za oči/zaščito za obraz. P302 + P352 PRI STIKU S KOŽO: umiti z veliko mila in vode. P333 + P313 Če nastopi draženje kože ali se pojavi izpuščaj: poiščite zdravniško pomoč/oskrbo. P501 Odstraniti vsebino/posodo v skladu z nacionalnimi predpisi. Sestavine po Uredbi o detergentih EC 648/2004 >5%: neionske površinsko aktivne snovi.",
    "price": "12,59 €",
    "badge": "Dekontaminacija",
    "sku": "DZ-CP015",
    "availability": "Dobavljivo pri dobavitelju – potrdimo pred naročilom",
    "delivery": "Po potrditvi dobavitelja",
    "shippingNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "brand": "Shiny Garage",
    "compatibility": "platišča in lakirane površine vozila",
    "orderNote": "Močnejše čistilo z indikatorjem delovanja; sredstvo se na površini ne sme zasušiti.",
    "checkoutEnabled": true,
    "cartEnabled": true,
    "checkoutAmount": 1259,
    "featured": false,
    "searchTerms": "shiny garage d-tox dtox 500ml platišča zračna rja zavorni prah kovinski delci indikator rdeče dekontaminacija",
    "image": "images/products/shiny-garage-d-tox-500ml.avif",
    "imageAlt": "Shiny Garage D-Tox 500ml",
    "theme": "linear-gradient(135deg, #b91c1c, #111827)"
  },
  {
    "name": "K2 Roton PRO",
    "category": "cistila",
    "categoryLabel": "Čistila",
    "description": "K2 Roton PRO je profesionalno detailing sredstvo za čiščenje platišč in odstranjevanje kovinskih delcev oziroma zračne rje iz lakiranih površin vozila. pH-nevtralna formula je varna za uporabo na vseh površinah, tudi na poliranih platiščih. Čistilo vsebuje indikator delovanja in se ob stiku s kovinskim delcem obarva rdeče. Deluje hitro in učinkovito, plastenka z merilno skalo omogoča nadzor nad vsebino, kakovostna pršilna glava pa omogoča dve vrsti curka in enakomeren nanos.\n\nNavodila za uporabo:\nSredstvo napršite na suho in ohlajeno površino. Pustite delovati 2–3 minute, da čistilo reagira s kovinskimi delci. V primeru kontaminacije se bo čistilo obarvalo rdeče. Za odstranjevanje trdovratnejših delcev si lahko pomagate z gobo ali krpo. Vozilo dobro sperite in operite s šamponom.\n\nVarnostni napotki:\nVsebuje alkohole C12-14, etoksilirane sulfate, natrijeve soli in natrijev merkaptoacetat. Nevarno: H315 Povzroča draženje kože. H318 Povzroča hude poškodbe oči. H317 Lahko povzroči alergijski odziv kože. P102 Hraniti zunaj dosega otrok. P280 Nositi zaščitne rokavice / zaščito za oči / zaščito za obraz. P264 Po uporabi temeljito umiti roke. P305 + P351 + P338 – PRI STIKU Z OČMI: previdno izpirajte z vodo nekaj minut. Odstranite kontaktne leče, če jih imate in če to lahko storite brez težav. Nadaljujte z izpiranjem. P302 + P352 PRI STIKU S KOŽO: umiti z veliko mila in vode. P501 Odstraniti vsebino/posodo v skladu z nacionalnimi predpisi. Sestavine po Uredbi o detergentih EC 648/2004 (>15%-<30%): neionske površinsko aktivne snovi; parfumi.",
    "price": "13,97 €",
    "badge": "Platišča",
    "sku": "DZ-CP016",
    "availability": "Dobavljivo pri dobavitelju – potrdimo pred naročilom",
    "delivery": "Po potrditvi dobavitelja",
    "shippingNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "brand": "K2",
    "compatibility": "platišča in lakirane površine vozila",
    "orderNote": "pH-nevtralno čistilo z indikatorjem delovanja.",
    "checkoutEnabled": true,
    "cartEnabled": true,
    "checkoutAmount": 1397,
    "featured": false,
    "searchTerms": "k2 roton pro platišča zračna rja kovinski delci ph nevtralno detailing indikator rdeče",
    "image": "images/products/k2-roton-pro-1000ml.avif",
    "imageAlt": "K2 Roton PRO čistilo za platišča 1000 ml",
    "theme": "linear-gradient(135deg, #dc2626, #111827)"
  },
  {
    "name": "Meguiar's Perfect Clarity Glass Cleaner 710ml",
    "category": "cistila",
    "categoryLabel": "Čistila",
    "description": "Profesionalno čistilo za stekla z izjemno močjo čiščenja. Deluje protiprašno, s stekla odbija prašne delce zato površina ostane čista dlje časa. Odličen je za odstranjevanje ostankov insektov, drevesne smole, sledi cigaretnega dima, ptičjih iztrebkov in ostale cestne umazanije. Primeren je tako za notranjo kot zunanjo uporabo. Njegova uporaba je zelo preprosta, za seboj pa pušča kristalno jasno površino.\n\nNavodila za uporabo:\nČistilo nanesite direktno na površino in obrišite z namensko mikro krpo za stekla. Krpo nato obrnite na čisto stran ter površino še enkrat prebrišite, da odstranite vse morebitne sledi čistila in umazanije. Po potrebi postopek ponovite.",
    "price": "14,99 €",
    "badge": "Stekla",
    "sku": "DZ-CP021",
    "availability": "Dobavljivo pri dobavitelju – potrdimo pred naročilom",
    "delivery": "Po potrditvi dobavitelja",
    "shippingNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "brand": "Meguiar's",
    "compatibility": "notranja in zunanja avtomobilska stekla",
    "orderNote": "710 ml; profesionalno čistilo za kristalno jasno površino stekel.",
    "checkoutEnabled": true,
    "cartEnabled": true,
    "checkoutAmount": 1499,
    "featured": false,
    "searchTerms": "meguiar's meguiars perfect clarity glass cleaner stekla insekti smola cigaretni dim ptičji iztrebki cestna umazanija 710ml",
    "image": "images/products/meguiar-s-perfect-clarity-glass-cleaner-710ml.avif",
    "imageAlt": "Meguiar's Perfect Clarity Glass Cleaner 710ml",
    "theme": "linear-gradient(135deg, #f59e0b, #111827)"
  },
  {
    "name": "CarPro Clarify 1L",
    "category": "cistila",
    "categoryLabel": "Čistila",
    "description": "CarPro Clarify je čistilo za odstranjevanje najtrdovratnejših madežev iz steklenih površin. Ne poškoduje predhodno nanešenih zaščitni premazov niti ne vpliva na njihovo delovanje. Zasnova je za odstranjevanje cestnega filma, maščob, oljnih madežev, prstnih odtisov, kontaminacije in ostale umazanije. Varen je za uporabo tako na zunanjih kot v notranjih površinah.\n\nNavodila za uporabo:\nČistilo nanesite na namensko mikro krpo za stekla kot npr. CarPro Glassfiber. Z vlažno stranjo krpe obrišite steklo, da odstranite večje delce umazanije. Krpo nato obrnite na čisto in suho stran ter površino še enkrat prebrišite, da odstranite vse morebitne ostanke umazanije. Po potrebi postopek ponovite.\n\nVarnostni napotki:\nP402 – Hraniti na suhem. P102 – Hraniti zunaj dosega otrok.",
    "price": "15,39 €",
    "badge": "Stekla",
    "sku": "DZ-CP022",
    "availability": "Dobavljivo pri dobavitelju – potrdimo pred naročilom",
    "delivery": "Po potrditvi dobavitelja",
    "shippingNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "brand": "CarPro",
    "compatibility": "notranja in zunanja stekla ter steklene površine",
    "orderNote": "1L; čistilo za stekla, varno za predhodno nanešene zaščitne premaze.",
    "checkoutEnabled": true,
    "cartEnabled": true,
    "checkoutAmount": 1539,
    "featured": false,
    "searchTerms": "carpro clarify 1l 1000ml stekla steklene površine cestni film maščoba oljni madeži prstni odtisi kontaminacija glass cleaner",
    "image": "images/products/carpro-clarify-1000ml.avif",
    "imageAlt": "CarPro Clarify 1L čistilo za stekla",
    "theme": "linear-gradient(135deg, #2563eb, #0f172a)"
  },
  {
    "name": "Carbon Collective Hybrid Glass Cleaner 250ml",
    "category": "cistila",
    "categoryLabel": "Čistila",
    "description": "Carbon Collective Hybrid Glass Cleaner je čistilo za stekla z dodano zaščito. V enem koraku odstranjuje vodne madeže in cestno umazanijo ter za seboj pušča hidrofoben sloj kateri odbija vodo ter poskrbi za varnejšo vožnjo. Učinek odtekanja vode se začne pri cca. 50km/h. Čistilo lahko uporabljate kot samostojno zaščito ali kot sredstvo za vzdrževanje površin zaščitenih s keramičnimi premazi ali sealanti. Čistilo je zelo enonomično, za celotno vozilo porabite le 20-30ml ter izjemno enostavno za uporabo. Za seboj pušča kristalno čisto površino brez madežev. Primeren je le za zunanjo uporabo.\n\nNavodila za uporabo:\nManjšo količino (1-2 pritiska na sprožilec) sredstva napršite direktno na stekleno površino in obrišite s čisto mikro krpo za stekla. Krpo nato obrnite na čisto stran in obrišite vse morebitne ostanke čistila. Svetujemo, da eno uro po nanosu čistila ne uporabljate brisalcev.\n\nVarnostni napotki:\nPozor: P262 – Preprečiti stik z očmi, kožo ali oblačili. P404 – Hraniti v zaprti posodi. P304 + P340 – PRI VDIHAVANJU: prenesti žrtev na svež zrak in jo pustiti počivati v položaju, ki olajša dihanje.",
    "price": "17,69 €",
    "badge": "Stekla",
    "sku": "DZ-CP023",
    "availability": "Dobavljivo pri dobavitelju – potrdimo pred naročilom",
    "delivery": "Po potrditvi dobavitelja",
    "shippingNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "brand": "Carbon Collective",
    "compatibility": "zunanje steklene površine vozila",
    "orderNote": "250 ml; čistilo za stekla z dodano hidrofobno zaščito, primerno le za zunanjo uporabo.",
    "checkoutEnabled": true,
    "cartEnabled": true,
    "checkoutAmount": 1769,
    "featured": false,
    "searchTerms": "carbon collective hybrid glass cleaner 250ml stekla hidrofobna zaščita vodni madeži cestna umazanija keramični premazi sealanti zunanja uporaba",
    "image": "images/products/carbon-collective-hybrid-glass-cleaner-250ml.avif",
    "imageAlt": "Carbon Collective Hybrid Glass Cleaner 250ml",
    "theme": "linear-gradient(135deg, #0f766e, #0f172a)"
  },
  {
    "name": "Fresso Glass Cleaner 500ml",
    "category": "cistila",
    "categoryLabel": "Čistila",
    "description": "Fresso predstavlja novo linijo visokokvalitetne avtokozmetike.\n\nGlass Cleaner je čistilo, namenjeno čiščenju vseh avtomobilskih stekel. Odstranjuje zapečene insekte, cestno in drugo umazanijo brez pretiranega drgnjenja. Je varno za uporabo na vseh avtomobilskih steklih, tudi zatemnjenih, saj ne vsebuje amoniaka. Hitro izpari in poskrbi za kristalno čista stekla. Njegov prijeten vonj pa poskrbi za prijetno delo.\n\nNavodila za uporabo:\nSredstvo nanesemo direktno na stekleno površino in dobro zbrišemo z mikro krpo za stekla ali kvalitetnim papirjem. Lahko nanesemo tudi na krpo in zbrišemo. V kolikor gre za zelo umazana stekla, postopek ponovimo. Pri delu priporočamo uporabo zaščitnih rokavic.\n\nVarnostni napotki:\n/",
    "price": "7,69 €",
    "badge": "Stekla",
    "sku": "DZ-CP029",
    "availability": "Dobavljivo pri dobavitelju – potrdimo pred naročilom",
    "delivery": "Po potrditvi dobavitelja",
    "shippingNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "brand": "Fresso",
    "compatibility": "vsa avtomobilska stekla, tudi zatemnjena stekla",
    "orderNote": "500 ml; čistilo za avtomobilska stekla brez amoniaka.",
    "checkoutEnabled": true,
    "cartEnabled": true,
    "checkoutAmount": 769,
    "featured": false,
    "searchTerms": "fresso glass cleaner 500ml stekla avtomobilska stekla zatemnjena stekla brez amoniaka insekti cestna umazanija avtokozmetika",
    "image": "images/products/fresso-glass-cleaner-500ml.avif",
    "imageAlt": "Fresso Glass Cleaner 500ml",
    "theme": "linear-gradient(135deg, #0ea5e9, #0f172a)"
  },
  {
    "name": "Onewax Lucidity Glass Cleaner 750ml",
    "category": "cistila",
    "categoryLabel": "Čistila",
    "description": "Onewax Lucidity namensko čistilo za avtomobilska stekla. Brez težav odstranjuje vso umazanijo, ki se nabere na steklih vozil. Odstranjuje zasušene ostanke insektov, maščobe in celo nikotinski film. Varen za uporabo na zunanji in notranji strani stekel. Zaradi svoje hitro hlapljive formule omogoča enostavno in hitro čiščenje brez lis. S svojo inovativno formulo je varen tudi do plastik in gume ob steklih, saj jih ne razbarva ali izsuši.\n\nNavodila za uporabo:\nSredstvo napršite direktno na površino ali ne namensko mikro krpo. Z namensko mikro krpo površino obrišite, da odstranite vse večje delce umazanije. Krpo nato obrnite na čisto stran in steklo dobro prebrišite, da odstranite vse sledi. Po potrebi postopek ponovite.",
    "price": "10,97 €",
    "badge": "Stekla",
    "sku": "DZ-CP030",
    "availability": "Dobavljivo pri dobavitelju – potrdimo pred naročilom",
    "delivery": "Po potrditvi dobavitelja",
    "shippingNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "brand": "Onewax",
    "compatibility": "zunanja in notranja avtomobilska stekla",
    "orderNote": "Hitro hlapljivo čistilo za stekla brez lis; varno za plastiko in gumo ob steklih.",
    "checkoutEnabled": true,
    "cartEnabled": true,
    "checkoutAmount": 1097,
    "featured": false,
    "searchTerms": "onewax lucidity glass cleaner stekla avtomobilska stekla insekti maščoba nikotin hitro hlapljivo brez lis 750ml",
    "image": "images/products/onewax-lucidity-glass-cleaner-750ml.avif",
    "imageAlt": "Onewax Lucidity Glass Cleaner 750ml",
    "theme": "linear-gradient(135deg, #0ea5e9, #0f172a)"
  },
  {
    "name": "Onewax Lucidity Glass Cleaner 5L",
    "category": "cistila",
    "categoryLabel": "Čistila",
    "description": "Onewax Lucidity namensko čistilo za avtomobilska stekla. Brez težav odstranjuje vso umazanijo, ki se nabere na steklih vozil. Odstranjuje zasušene ostanke insektov, maščobe in celo nikotinski film. Varen za uporabo na zunanji in notranji strani stekel. Zaradi svoje hitro hlapljive formule omogoča enostavno in hitro čiščenje brez lis. S svojo inovativno formulo je varen tudi do plastik in gume ob steklih, saj jih ne razbarva ali izsuši.\n\nNavodila za uporabo:\nSredstvo napršite direktno na površino ali na namensko mikro krpo. Z namensko mikro krpo površino obrišite, da odstranite vse večje delce umazanije. Krpo nato obrnite na čisto stran in steklo dobro prebrišite, da odstranite vse sledi. Po potrebi postopek ponovite.\n\nVarnostni napotki:\n/",
    "price": "40,97 €",
    "badge": "Stekla",
    "sku": "DZ-CP031",
    "availability": "Dobavljivo pri dobavitelju – potrdimo pred naročilom",
    "delivery": "Po potrditvi dobavitelja",
    "shippingNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "brand": "Onewax",
    "compatibility": "zunanja in notranja avtomobilska stekla",
    "orderNote": "5L; hitro hlapljivo čistilo za stekla brez lis, varno za plastiko in gumo ob steklih.",
    "checkoutEnabled": true,
    "cartEnabled": true,
    "checkoutAmount": 4097,
    "featured": false,
    "searchTerms": "onewax lucidity glass cleaner 5l stekla avtomobilska stekla insekti maščoba nikotin hitro hlapljivo brez lis plastika guma",
    "image": "images/products/onewax-lucidity-glass-cleaner-5l.avif",
    "imageAlt": "Onewax Lucidity Glass Cleaner 5L",
    "theme": "linear-gradient(135deg, #0284c7, #0f172a)"
  },
  {
    "name": "Chemical Guys Hydro View Glass Ceramic 473ml",
    "category": "cistila",
    "categoryLabel": "Čistila",
    "description": "Chemical Guys Hydroview ceramic glass Cleaner je moderno sredstvo za čiščenje stekel, katero vsebuje zaščito za stekla. Gre za kombinacijo čistila in keramičnega premaza, ki je izredno enostaven za nanos. V enem koraku z njim stekla očistimo in ob enem še zaščitimo. Znatno izboljša vidljivost v slabih vremenskih pogojih. Unikatne sestavine, katere vsebujejo keramične delce odbijajo vodo in zagotavljajo dobro zaščito stekel. Ravno tako pa omogoča enostavneje čiščenje stekel po predhodnem nanosu sredstva Hydroview. Vrhunsko sredstvo, katero v enem koraku omogoča hitro in enostavno čiščenje stekel brez sledi ter zaščito za stekla v enem.\n\nNavodila za uporabo:\nPred uporabo plastenko dobro pretresemo. Napršimo iz razdalje 15-20 cm direktno na stekla ali na mikro krpo. Čistilo nato z krpo razmažemo po steklu in obrišemo do suhega. V kolikor je potrebno uporabimo še eno suho mikro krpo. V kolikor so stekla zelo umazana priporočamo predhodno čiščenje z namenskim čistilom za stekla.\n\nVarnostni napotki:\nP101 Če je potreben zdravniški nasvet, mora biti na voljo posoda ali etiketa proizvod. P102 Hraniti zunaj dosega otrok. P301 + P312 PRI ZAUŽITJU: ob slabem počutju pokličite CENTER ZA ZASTRUPITVE ali zdravnika. P305 + P351 + P338 PRI STIKU Z OČMI: previdno izpirajte z vodo nekaj minut. Odstranite kontaktne leče, če jih imate in če to lahko storite brez težav. Nadaljujte z izpiranjem. P337 + P313 Če draženje oči ne preneha: poiščite zdravniško pomoč/oskrbo.",
    "price": "31,99 €",
    "badge": "Keramična zaščita stekel",
    "sku": "DZ-CP032",
    "availability": "Dobavljivo pri dobavitelju – potrdimo pred naročilom",
    "delivery": "Po potrditvi dobavitelja",
    "shippingNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "brand": "Chemical Guys",
    "compatibility": "stekla in zunanje steklene površine vozila",
    "orderNote": "473 ml; čistilo in keramična zaščita stekel v enem koraku.",
    "checkoutEnabled": true,
    "cartEnabled": true,
    "checkoutAmount": 3199,
    "featured": false,
    "searchTerms": "chemical guys hydro view hydroview glass ceramic stekla keramična zaščita čistilo vidljivost dež 473ml",
    "image": "https://chemicalguys.co.uk/cdn/shop/files/CLD30116-hydroview-ceramic-glass-cleaner-coating.jpg?v=1758629278&width=1946",
    "imageAlt": "Chemical Guys Hydro View Glass Ceramic 473ml",
    "theme": "linear-gradient(135deg, #0891b2, #0f172a)"
  },
  {
    "name": "K2 Felix 750ml",
    "category": "cistila",
    "categoryLabel": "Čistila",
    "description": "Pripravljeno čistilo za platišča in trdovratno umazanijo pri zunanjem čiščenju.",
    "price": "4,59 €",
    "regularPrice": "4,97 €",
    "supplierPrice": "3,23 €",
    "badge": "Platišča",
    "sku": "2026-05",
    "availability": "Dobavljivo pri dobavitelju – potrdimo pred naročilom",
    "delivery": "Po potrditvi dobavitelja",
    "shippingNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "purchaseUrl": "https://www.operi-avto.si/pripravljeno-za-uporabo/50-k2-felix-5906534000781.html",
    "brand": "K2",
    "compatibility": "univerzalno za nego vozila",
    "orderNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "checkoutEnabled": true,
    "checkoutAmount": 459,
    "featured": false,
    "searchTerms": "k2 felix platišča pripravljeno čistilo zunanjost",
    "image": "https://www.operi-avto.si/15821-large_default/k2-felix.jpg",
    "imageAlt": "K2 Felix 750ml",
    "theme": "linear-gradient(135deg, #15803d, #0f172a)",
    "cartEnabled": true
  },
  {
    "name": "Flex VC 21 L MC 1250W",
    "category": "orodja",
    "categoryLabel": "Orodja",
    "description": "Flex VC 21 L MC je priročen in kompakten sesalec, ki je enostaven za uporabo in prenašanje. Visoko zmogljiva turbina zagotavlja visoko sesalno moč in vakum. Mehak zagon preprečuje prenapetost (5 sekund) in v tem času odstrani vso umazanijo iz sesalne cevi. Sesalec je opremljen tudi z 220V vtičnico za ostale stroje. Na zgornjem delu se nahaja gumb, ki ustavi sesanje. Sesalec omogoča tudi izpihovanje zraka, in je tako odličen pripomoček za odstranjevanje vode z vozil, odstranjevanje listja,... Prostornina posode sesalca je 20L, posesate pa lahko 11L tekočine. Flex VC 21 L MC je odličen pripomoček za čiščenje vozil, delavnic, poslovnih prostorov in še in še.\n\nSpecifikacije:\n- Vhodna moč: 1250W\n- Max. volumen pretoka: 3600L /min\n- Max. vakum: 21000 Pa\n- Površina filtra: 3000 qcm\n- Volumen posode: 20L\n- Kapaciteta za tekočine: 11L\n- Dimenzije (ŠxDxV): 387 x 377 x 506mm\n- Teža: 6,7kg\n\nVsebina kompleta:\n- 1x Sesalec Flex VC 21 L MC\n- 1x Sesalna cev 3,5m\n- 2x Aluminijast podaljšek\n- 1x Ozek nastavek\n- 1x Krtača za tla\n- 1x Širok nastavek\n- 1x Okrogel krtačni nastavek\n- 1x Držalo za električni kabel\n- 1x Vrečka\n\nGarancijski rok: 2 leti od datuma nakupa",
    "price": "249,99 €",
    "badge": "Sesalec",
    "sku": "DZ-T01",
    "availability": "Dobavljivo pri dobavitelju – potrdimo pred naročilom",
    "delivery": "Po potrditvi dobavitelja",
    "shippingNote": "Poštnina 5,90 €; nad 60 € brezplačna poštnina",
    "brand": "Flex",
    "compatibility": "čiščenje vozil, delavnic in poslovnih prostorov",
    "orderNote": "Garancijski rok: 2 leti od datuma nakupa.",
    "checkoutEnabled": true,
    "cartEnabled": true,
    "checkoutAmount": 24999,
    "featured": false,
    "searchTerms": "flex vc 21 l mc 1250w sesalec mokro suho izpihovanje delavnica vozila 20l 11l",
    "image": "images/products/sesalnik-flex-vc-21-m-c.avif",
    "imageAlt": "Flex VC 21 L MC 1250W sesalec",
    "theme": "linear-gradient(135deg, #dc2626, #111827)"
  }
];
