(() => {
const statuses={draft:'Osnutek',preparing:'V pripravi',published:'Objavljeno',reserved:'Rezervirano',sold:'Prodano',withdrawn:'Umaknjeno'};
const checks={documentation:'Dokumentacija',serviceHistory:'Servisna zgodovina',condition:'Stanje vozila',photos:'Fotografije',price:'Cena',commissionPermission:'Dovoljenje za objavo (komisija)'};
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); let vehicles=[];
const request=async(path,options={})=>{const r=await fetch('/api/team/admin/vehicles'+path,{...options,cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Zahteva ni uspela.');return d};
const render=()=>{const q=$('[data-vehicle-search]').value.toLowerCase(),f=$('[data-vehicle-status-filter]').value,sort=$('[data-vehicle-sort]').value;let rows=vehicles.filter(v=>(!f||v.status===f)&&`${v.make} ${v.model} ${v.location}`.toLowerCase().includes(q));rows.sort(sort==='make'?(a,b)=>a.make.localeCompare(b.make):sort==='price'?(a,b)=>(b.price_cents||0)-(a.price_cents||0):(a,b)=>b.updated_at.localeCompare(a.updated_at));$('#vehicle-stats').innerHTML=Object.entries(statuses).map(([k,v])=>`<span><b>${vehicles.filter(x=>x.status===k).length}</b> ${v}</span>`).join('');$('#vehicle-list').innerHTML=rows.map(v=>`<article class="vehicle-row"><div><b>${esc(v.make)} ${esc(v.model)} ${esc(v.variant)}</b><p>${esc(statuses[v.status])} · ${Number(v.mileage||0).toLocaleString('sl-SI')} km · ${v.price_cents?new Intl.NumberFormat('sl-SI',{style:'currency',currency:'EUR'}).format(v.price_cents/100):'cena ni določena'}</p><small>Zadnja sprememba: ${new Date(v.updated_at).toLocaleString('sl-SI')} ${v.is_public?'· javno':'· ni javno'}</small></div><button data-edit="${v.id}">Odpri</button></article>`).join('')||'<p>Ni vozil za izbrane pogoje.</p>'};
const load=async()=>{try{vehicles=(await request('')).vehicles;render()}catch(e){$('#vehicle-list').textContent=e.message}};
const open=v=>{const f=$('[data-vehicle-form]');f.reset();for(const [k,val] of Object.entries(v||{})){const camel=k.replace(/_([a-z])/g,(_,c)=>c.toUpperCase());if(f.elements[camel]&&typeof val!=='object')f.elements[camel].value=val??''}f.elements.id.value=v?.id||'';f.elements.priceEuros.value=v?.price_cents? v.price_cents/100:'';f.elements.acquisitionCostEuros.value=v?.acquisition_cost_cents?v.acquisition_cost_cents/100:'';f.elements.isPublic.checked=Boolean(v?.is_public);Object.keys(checks).forEach(k=>f.elements[k].checked=Boolean(v?.checklist?.[k]));$('[data-photo-area]').classList.toggle('hidden',!v);renderPhotos(v);$('#vehicle-dialog').showModal()};
const renderPhotos=v=>{$('[data-photo-list]').innerHTML=(v?.images||[]).map((i,index,images)=>`<div class="photo-card"><img src="/api/team/admin/vehicles/${v.id}/images/${i.id}" alt="Predogled"><button type="button" data-primary="${i.id}">${i.is_primary?'Glavna ✓':'Nastavi glavno'}</button><button type="button" data-move="${i.id}" data-direction="-1"${index===0?' disabled':''}>←</button><button type="button" data-move="${i.id}" data-direction="1"${index===images.length-1?' disabled':''}>→</button><button type="button" data-delete-photo="${i.id}">Odstrani</button></div>`).join('')};
window.addEventListener('dz:admin-ready',load);$('[data-status-select]').innerHTML=Object.entries(statuses).map(([k,v])=>`<option value="${k}">${v}</option>`).join('');$('[data-vehicle-status-filter]').innerHTML+=$('[data-status-select]').innerHTML;$('[data-checklist]').innerHTML+=Object.entries(checks).map(([k,v])=>`<label class="check"><input type="checkbox" name="${k}"> ${v}</label>`).join('');
$('[data-new-vehicle]').onclick=()=>open();document.addEventListener('input',e=>{if(e.target.matches('[data-vehicle-search]'))render()});document.addEventListener('change',e=>{if(e.target.matches('[data-vehicle-status-filter],[data-vehicle-sort]'))render()});document.addEventListener('click',async e=>{if(e.target.dataset.edit)return open(vehicles.find(v=>v.id===e.target.dataset.edit));const f=$('[data-vehicle-form]'),id=f.elements.id.value;try{if(e.target.dataset.deletePhoto){await request(`/${id}/images/${e.target.dataset.deletePhoto}`,{method:'DELETE'});await load();open(vehicles.find(v=>v.id===id))}if(e.target.dataset.primary){await request(`/${id}/images/${e.target.dataset.primary}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({isPrimary:true})});await load();open(vehicles.find(v=>v.id===id))}if(e.target.dataset.move){const vehicle=vehicles.find(v=>v.id===id),order=vehicle.images.map(image=>image.id),from=order.indexOf(e.target.dataset.move),to=from+Number(e.target.dataset.direction);[order[from],order[to]]=[order[to],order[from]];await request(`/${id}/images`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({imageOrder:order})});await load();open(vehicles.find(v=>v.id===id))}}catch(x){$('[data-vehicle-message]').textContent=x.message}});
$('[data-vehicle-form]').addEventListener('submit',async e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const fd=new FormData(e.target),id=fd.get('id'),body=Object.fromEntries(fd);body.priceCents=Math.round(Number(body.priceEuros||0)*100);body.acquisitionCostCents=Math.round(Number(body.acquisitionCostEuros||0)*100);body.isPublic=fd.has('isPublic');body.checklist=Object.fromEntries(Object.keys(checks).map(k=>[k,fd.has(k)]));try{const d=await request(id?`/${id}`:'',{method:id?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});await load();open(vehicles.find(v=>v.id===(id||d.id)))}catch(x){$('[data-vehicle-message]').textContent=x.message}});
$('[data-photo-input]').addEventListener('change',async e=>{const id=$('[data-vehicle-form]').elements.id.value;for(const file of [...e.target.files]){const fd=new FormData();fd.set('image',file);try{await request(`/${id}/images`,{method:'POST',body:fd})}catch(x){$('[data-vehicle-message]').textContent=x.message;break}}await load();open(vehicles.find(v=>v.id===id))});
})();
